### ISSUE TITLE
Document libjpeg/zlib etc as dependencies of PIL; add a runserver check for their presence

### ISSUE THREAD

**Issue by btipling** [torchbox/wagtaildemo#12] opened 2014-02-14 13:41 UTC
Is this expected?

![2014-02-14 at 5 39 am 2x](https://f.cloud.github.com/assets/249641/2171147/a108d4b6-957d-11e3-8eaa-6f6efb733219.png)

**Comment by BertrandBordage** [comment] 2015-02-05 16:45
I can’t reproduce this bug.  Maybe it’s a file/folder permission issue?

**Comment by gasman** [comment] 2015-02-05 18:46
It sounds like this is universally caused by missing dependencies of PIL. Have updated the issue title to address the fixes that @btipling proposes.

**Comment by BertrandBordage** [comment] 2015-02-05 20:11
So this could be closed in favor of #7 if I understand well.

**Comment by gasman** [comment] 2015-08-26 12:09
http://docs.wagtail.io/en/v1.0/getting_started/index.html now covers the fact that Pillow requires additional libraries (and this document is the current recommended route for new users, rather than wagtaildemo). Adding a runserver check is covered in https://github.com/torchbox/wagtail/issues/1644.

**Closed by gasman** 2015-08-26 12:09 UTC
