### ISSUE TITLE
/bin/sh: 1: django_libsass.SassCompiler: not found

### ISSUE THREAD

**Issue by contradictioned** [torchbox/wagtaildemo#55] opened 2015-02-05 19:35 UTC
I have the same problem as #39, but the solution to install libsass does not apply for me.  My pip freeze output is:

    Django==1.7.4
    django-appconf==0.6
    django-compressor==1.4
    django-libsass==0.2
    libsass==0.6.2
    six==1.9.0

When I start the development server `python manage.py runserver` everything is fine, but when I use Apache and wsgi, the error occurs during template rendering:

    /bin/sh: 1: django_libsass.SassCompiler: not found

I am using virtualenv, python3, and according to the debug output, the virtualenv is found in the python path. Any hints? Thanks :)

**Comment by gasman** [comment] 2015-02-05 20:24
Hi @contradictioned,
To isolate the problem, please try running the following line in the Python shell:

    import sass; sass

The expected result is something like `<module 'sass' from '.../lib/python3.4/site-packages/libsass-0.6.2-py3.4-linux-i686.egg/sass.py'>`. If this fails with an error instead, the problem is somewhere in [libsass-python](https://github.com/dahlia/libsass-python/) library or the underlying libsass C++ library, and I'd suggest troubleshooting further by trying `pip install libsass` in a fresh virtualenv - looking out for any error messages during the build - and retrying that line.

If that line succeeds when you first try it, please run the following within `./manage.py shell` and let me know the output:

    from django_libsass import SassCompiler

**Comment by contradictioned** [comment] 2015-02-05 22:53
Hey,

`import sass; sass` produces `<module 'sass'>...`
and `from django_libsass import SassCompiler` produces nothing (so, loads correctly), and django_libsass.SassCompiler is recognized as class.

**Comment by gasman** [comment] 2015-02-09 15:18
Ah, I see... sorry, I missed the comment about it working successfully through `runserver` but not Apache. It sounds like this is more of a configuration issue than a Wagtail bug, but to investigate this further I would suggest putting those lines (`import sass; sass` and `from django_libsass import SassCompiler`) into your `settings/base.py` file - hopefully that will give you a more informative error message. (The error thrown by django-compressor is a bit misleading, because it attempts to load django_libsass.SassCompiler as a module first, and if that fails, it attempts to run "django_libsass.SassCompiler" as a command instead - the error you see is from the second attempt.)

**Comment by gasman** [comment] 2015-02-18 11:47
Closing this as it's external to Wagtail. See also https://groups.google.com/d/msg/wagtail/bmz9t8If2RA/7EAhdVUOd24J which reports the same symptoms and provides some additional detail.

**Closed by gasman** 2015-02-18 11:47 UTC

**Comment by gasman** [comment] 2015-08-12 14:10
I've now put together a wiki page detailing steps to try when encountering this error: [Troubleshooting `/bin/sh: django_libsass.SassCompiler: command not found`](https://github.com/torchbox/django-libsass/wiki/Troubleshooting)
